---
- name: Pkg| `curl` installed
  become: yes
  package:
    name: curl
    state: present

- name: Pkg| `ghcup` installed
  # Installation respects XDG standard.
  shell: |
    GHCUP_USE_XDG_DIRS=Yes
    export GHCUP_USE_XDG_DIRS
    curl --proto '=https' --tlsv1.2 -sSf https://get-ghcup.haskell.org | sh
