---
- name: Pkg| `curl` installed
  become: yes
  package:
    name: curl
    state: present

# GCC is mandatory, as it is runtime dependency
- name: Pkg| `gcc` installed
  become: yes
  package:
    name: gcc
    state: present

# TODO: Make is a build-time dependency, if it was not installed before - purge it after the transaction
- name: Pkg| `make` installed
  become: yes
  package:
    name: gcc
    state: present

- name: Fix| Creating a ~/.local/ghcup
  file:
    path: "{{ lookup('env', 'HOME') }}/.local/share/ghcup"
    state: directory

- name: Pkg| `ghcup` installed
  shell: |
    # Installation respects XDG standard.
    GHCUP_USE_XDG_DIRS=True
    export GHCUP_USE_XDG_DIRS
    # Bail if command before pipe fails
    set -o pipefail
    export BOOTSTRAP_HASKELL_NONINTERACTIVE=True
    curl --proto '=https' --tlsv1.2 -sSf https://get-ghcup.haskell.org | sh
