---
- name: Pkg| `curl` installed
  become: yes
  package:
    name: curl
    state: present

- name: Pkg| `ghcup` installed
  shell: |
    # Installation respects XDG standard.
    GHCUP_USE_XDG_DIRS=Yes
    export GHCUP_USE_XDG_DIRS
    # Bail if command before pipe fails
    set -o pipefail
    curl --proto '=https' --tlsv1.2 -sSf https://get-ghcup.haskell.org | sh
